"""Inicial: productos e historial

Revision ID: b67d858cd396
Revises: 
Create Date: 2025-10-20 23:59:39.987033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b67d858cd396'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telegram_transcripciones_id', table_name='telegram_transcripciones')
    op.drop_index('ix_telegram_transcripciones_message_id', table_name='telegram_transcripciones')
    op.drop_table('telegram_transcripciones')
    op.drop_index('ix_acciones_pendientes_id', table_name='acciones_pendientes')
    op.drop_table('acciones_pendientes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acciones_pendientes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accion', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('params_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('mensaje_original', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', postgresql.ENUM('pendiente_confirmacion', 'confirmada', 'cancelada', 'ejecutada', 'error', name='estadoaccion'), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_confirmacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='acciones_pendientes_pkey')
    )
    op.create_index('ix_acciones_pendientes_id', 'acciones_pendientes', ['id'], unique=False)
    op.create_table('telegram_transcripciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('texto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('procesado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='telegram_transcripciones_pkey')
    )
    op.create_index('ix_telegram_transcripciones_message_id', 'telegram_transcripciones', ['message_id'], unique=False)
    op.create_index('ix_telegram_transcripciones_id', 'telegram_transcripciones', ['id'], unique=False)
    # ### end Alembic commands ###
